version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: listify-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=listify
      - MONGO_INITDB_ROOT_PASSWORD=listify_password
    restart: unless-stopped
    
  redis:
    image: redis:latest
    container_name: listify-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data: 